DATASET_NUM_DIMS = 31

IDX_CLASS_ID = 0
IDX_LOCATION = 1
IDX_LANDMARKS = 5
IDX_EYE_STATUS = 15
IDX_OCCLUSIONS = 17
IDX_BLUR = 24
IDX_ILLUMINATION = 25
IDX_COMPLETENESS = 26
IDX_AGE = 27
IDX_GENDER = 28
IDX_GLASSES = 29
IDX_MASK = 30
